// ============================================
// Temporary placeholder sprites — replaced by Phase 4 assets
// ============================================

import { createSprite } from '../engine/spriteUtils';
import type { Sprite, SpriteSheet, AnimationDef } from '../engine/types';

// --- Hunter stub sprites (Bloodborne character) ---

const HUNTER_PALETTE: Record<string, string> = {
  'H': '#1a1015', // hat
  'F': '#d4b896', // face/skin
  'C': '#2a2030', // coat
  'B': '#1a1015', // boots
  'W': '#888888', // weapon (metal)
  'E': '#ffffff', // eyes
  'G': '#d4a017', // glow/accent
  '.': '',        // transparent (handled by createSprite)
};

const hunterIdle1 = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
...CCCCCC...
..CCCCCCCC..
..CCCCCCCC..
..CCCCCCCC..
...CCCCCC...
...CC..CC...
...CC..CC...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, HUNTER_PALETTE);

const hunterIdle2 = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
...CCCCCC...
..CCCCCCCC..
..CCCCCCCC..
..CCCCCCCC..
...CCCCCC...
...CC..CC...
...CC..CC...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, HUNTER_PALETTE);

const hunterWalk1 = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
...CCCCCC...
..CCCCCCCC..
..CCCCCCCC..
..CCCCCCCC..
...CCCCCC...
...CC..CC...
..CC....CC..
..BB....BB..
.BB......BB.
.BBB....BBB.
`, HUNTER_PALETTE);

const hunterWalk2 = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
...CCCCCC...
..CCCCCCCC..
..CCCCCCCC..
..CCCCCCCC..
...CCCCCC...
..CC....CC..
...CC..CC...
...BB..BB...
..BB....BB..
.BBB....BBB.
`, HUNTER_PALETTE);

const hunterInscribe = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
...CCCCCCWW.
..CCCCCCWWW.
..CCCCCC.WW.
..CCCCCC....
...CCCCCC...
...CC..CC...
...CC..CC...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, HUNTER_PALETTE);

const hunterRead = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FFEF....
....FFFF....
.WWCCCCCC...
.WWCCCCCCC..
.WWCCCCCCC..
..CCCCCCCC..
...CCCCCC...
...CC..CC...
...CC..CC...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, HUNTER_PALETTE);

const hunterForge = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
...CCCCCC.WW
..CCCCCC.WWW
..CCCCCC.WWW
..CCCCCC..WW
...CCCCCC...
...CC..CC...
...CC..CC...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, HUNTER_PALETTE);

const hunterMeditate = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
..GCCCCCCG..
..CCCCCCCC..
..CCCCCCCC..
..CCCCCCCC..
...CCCCCC...
..CCCCCCCC..
..CC....CC..
..BB....BB..
..BBBBBBBB..
..BBBBBBBB..
`, HUNTER_PALETTE);

const hunterStagger = createSprite(`
.....HHHH...
....HHHHHH..
....HHHHHHH.
.....FFFF...
.....FEEF...
.....FFFF...
....CCCCCC..
...CCCCCCCC.
...CCCCCCCC.
..CCCCCCCCC.
...CCCCCC...
...CC..CC...
..CC....CC..
..BB....BB..
.BB......BB.
.BBB....BBB.
`, HUNTER_PALETTE);

const hunterVictory = createSprite(`
....HHHH....
...HHHHHH...
...HHHHHHH..
....FFFF....
....FEEF....
....FFFF....
.WWCCCCCCWW.
.WWCCCCCWWW.
..CCCCCCCC..
..CCCCCCCC..
...CCCCCC...
...CC..CC...
...CC..CC...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, HUNTER_PALETTE);

const hunterRest = createSprite(`
................
................
................
................
................
................
................
....HHHHFFFF....
...HHHHHHFFFF...
..CCCCCCCCCCCC..
..CCCCCCCCCCCC..
..CCCCCCCCCCCC..
.BBBCCCCCCBBB...
.BBB......BBB...
................
................
`, HUNTER_PALETTE);

export const stubHunterSheet: SpriteSheet = {
  sprites: {
    'idle_1': hunterIdle1,
    'idle_2': hunterIdle2,
    'walk_1': hunterWalk1,
    'walk_2': hunterWalk2,
    'inscribe_1': hunterInscribe,
    'inscribe_2': hunterIdle1,
    'read_1': hunterRead,
    'read_2': hunterIdle1,
    'forge_1': hunterForge,
    'forge_2': hunterIdle1,
    'meditate_1': hunterMeditate,
    'meditate_2': hunterIdle1,
    'stagger_1': hunterStagger,
    'stagger_2': hunterIdle1,
    'victory_1': hunterVictory,
    'victory_2': hunterIdle1,
    'rest_1': hunterRest,
    'enter_1': hunterWalk1,
    'enter_2': hunterWalk2,
    'exit_1': hunterWalk1,
    'exit_2': hunterWalk2,
  },
};

export const stubHunterAnims: Record<string, AnimationDef> = {
  idle:      { frames: ['idle_1', 'idle_2'], frameDuration: 0.8, loop: true },
  walk:      { frames: ['walk_1', 'walk_2'], frameDuration: 0.25, loop: true },
  inscribe:  { frames: ['inscribe_1', 'inscribe_2'], frameDuration: 0.4, loop: true },
  read:      { frames: ['read_1', 'read_2'], frameDuration: 0.5, loop: true },
  forge:     { frames: ['forge_1', 'forge_2'], frameDuration: 0.3, loop: true },
  meditate:  { frames: ['meditate_1', 'meditate_2'], frameDuration: 0.6, loop: true },
  stagger:   { frames: ['stagger_1', 'stagger_2'], frameDuration: 0.15, loop: true },
  victory:   { frames: ['victory_1', 'victory_2'], frameDuration: 0.5, loop: true },
  rest:      { frames: ['rest_1'], frameDuration: 1.0, loop: true },
  enter:     { frames: ['enter_1', 'enter_2'], frameDuration: 0.25, loop: true },
  exit:      { frames: ['exit_1', 'exit_2'], frameDuration: 0.25, loop: true },
};

// --- Knight stub sprites (Dark Souls / Elden Ring character) ---

const KNIGHT_PALETTE: Record<string, string> = {
  'A': '#6a6a7a', // armor
  'H': '#7a7a8a', // helmet
  'P': '#882020', // plume
  'V': '#111111', // visor
  'S': '#999999', // sword
  'D': '#aa8800', // gold detail
  'K': '#4a2020', // cape
  'L': '#5a5a6a', // legs
  'B': '#3a3a40', // boots
  'G': '#ff8c00', // glow/accent
  '.': '',
};

const knightIdle1 = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
...AAAAAA...
..AAAAAAAA..
.KAAAAAAAAK.
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
...LL..LL...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, KNIGHT_PALETTE);

const knightIdle2 = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
...AAAAAA...
..AAAAAAAA..
.KAAAAAAAAK.
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
...LL..LL...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, KNIGHT_PALETTE);

const knightWalk1 = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
...AAAAAA...
..AAAAAAAA..
.KAAAAAAAAK.
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
..LL....LL..
.LL......LL.
.BB......BB.
.BB......BB.
BBB......BBB
`, KNIGHT_PALETTE);

const knightWalk2 = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
...AAAAAA...
..AAAAAAAA..
.KAAAAAAAAK.
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
..LL....LL..
..BB....BB..
.BB......BB.
BBB......BBB
`, KNIGHT_PALETTE);

const knightInscribe = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
...AAAAAASS.
..AAAAAAAAS.
.KAAAAAAAA..
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
...LL..LL...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, KNIGHT_PALETTE);

const knightRead = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
.SSAAAAAA...
.SSAAAAAAA..
..KAAAAAAAAK
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
...LL..LL...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, KNIGHT_PALETTE);

const knightForge = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
...AAAAAASSS
..AAAAAAASSS
.KAAAAAAAASS
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
...LL..LL...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, KNIGHT_PALETTE);

const knightMeditate = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
..GAAAAAG...
..AAAAAAAA..
.KAAAAAAAAK.
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
..AAAAAAAA..
..LL....LL..
..BB....BB..
..BBBBBBBB..
..BBBBBBBB..
`, KNIGHT_PALETTE);

const knightStagger = createSprite(`
.....PPPP...
....HHHHHH..
...HHHHHHHH.
...HHVVVVHH.
...HHHHHHHH.
....AAAAAA..
...AAAAAAAA.
..KAAAAAAAA.
..KAAAAAAAAK
...AAAAAAAA.
....AAAAAA..
...LL...LL..
..LL.....LL.
..BB.....BB.
.BB.......BB
.BBB.....BBB
`, KNIGHT_PALETTE);

const knightVictory = createSprite(`
....PPPP....
...HHHHHH...
..HHHHHHHH..
..HHVVVVHH..
..HHHHHHHH..
SSAAAAAAAADD
SSAAAAAAAADD
.KAAAAAAAAK.
.KAAAAAAAAK.
..AAAAAAAA..
...AAAAAA...
...LL..LL...
...LL..LL...
...BB..BB...
...BB..BB...
..BBB..BBB..
`, KNIGHT_PALETTE);

const knightRest = createSprite(`
................
................
................
................
................
................
................
...HHHHAAAAAA...
..HHHHAAAAAAAA..
.KKAAAAAAAAAAK..
.KKAAAAAAAAAAK..
..AAAAAAAAAAA...
.BBBLLLLLLBBB...
.BBB......BBB...
................
................
`, KNIGHT_PALETTE);

export const stubKnightSheet: SpriteSheet = {
  sprites: {
    'idle_1': knightIdle1,
    'idle_2': knightIdle2,
    'walk_1': knightWalk1,
    'walk_2': knightWalk2,
    'inscribe_1': knightInscribe,
    'inscribe_2': knightIdle1,
    'read_1': knightRead,
    'read_2': knightIdle1,
    'forge_1': knightForge,
    'forge_2': knightIdle1,
    'meditate_1': knightMeditate,
    'meditate_2': knightIdle1,
    'stagger_1': knightStagger,
    'stagger_2': knightIdle1,
    'victory_1': knightVictory,
    'victory_2': knightIdle1,
    'rest_1': knightRest,
    'enter_1': knightWalk1,
    'enter_2': knightWalk2,
    'exit_1': knightWalk1,
    'exit_2': knightWalk2,
  },
};

export const stubKnightAnims: Record<string, AnimationDef> = {
  idle:      { frames: ['idle_1', 'idle_2'], frameDuration: 0.8, loop: true },
  walk:      { frames: ['walk_1', 'walk_2'], frameDuration: 0.25, loop: true },
  inscribe:  { frames: ['inscribe_1', 'inscribe_2'], frameDuration: 0.4, loop: true },
  read:      { frames: ['read_1', 'read_2'], frameDuration: 0.5, loop: true },
  forge:     { frames: ['forge_1', 'forge_2'], frameDuration: 0.3, loop: true },
  meditate:  { frames: ['meditate_1', 'meditate_2'], frameDuration: 0.6, loop: true },
  stagger:   { frames: ['stagger_1', 'stagger_2'], frameDuration: 0.15, loop: true },
  victory:   { frames: ['victory_1', 'victory_2'], frameDuration: 0.5, loop: true },
  rest:      { frames: ['rest_1'], frameDuration: 1.0, loop: true },
  enter:     { frames: ['enter_1', 'enter_2'], frameDuration: 0.25, loop: true },
  exit:      { frames: ['exit_1', 'exit_2'], frameDuration: 0.25, loop: true },
};
