// ============================================
// Scene Props — interactive and decorative sprite-based objects
// ============================================

import { createSprite } from '../engine/spriteUtils';
import type { Sprite } from '../engine/types';
import type { AnimationState } from '@claudeborne/shared';

// ============================================
// Prop interface
// ============================================

export interface ScenePropDef {
  name: string;
  sprite: Sprite;
  /** Position in tile coordinates (top-left corner) */
  tileX: number;
  tileY: number;
  /** Which animation state this prop is associated with */
  actionState?: AnimationState;
}

// ============================================
// Hunter's Workshop Props
// ============================================

const WORKSHOP_PAL: Record<string, string> = {
  'W': '#5a3d2b',  // wood
  'w': '#6a4d3b',  // wood highlight
  'D': '#3d2b1f',  // dark wood
  'd': '#4a3828',  // dark wood highlight
  'M': '#888888',  // metal
  'm': '#aaaaaa',  // metal highlight
  'R': '#882020',  // red (blood vials)
  'r': '#aa3030',  // red highlight
  'G': '#d4a017',  // golden glow
  'g': '#b88a10',  // golden dim
  'B': '#333333',  // black
  'b': '#444444',  // dark grey
  'V': '#772020',  // vial glass
  'v': '#993333',  // vial highlight
  'P': '#553322',  // paper/parchment
  'p': '#664433',  // paper highlight
  'L': '#d4a017',  // lantern light
  'l': '#ffcc44',  // lantern bright
  'C': '#666666',  // chain
  'c': '#888888',  // chain bright
  'K': '#1a1015',  // very dark
  'S': '#999999',  // steel
  's': '#bbbbbb',  // steel highlight
};

// Workbench (3x2 tiles = 48x32 pixels) — inscribe/edit happens here
const workbench = createSprite(`
wwwwwwwwWWWWwwwwwwWWWWwwwwwwwwwwwwWWWWwwwwwwwwwwww
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWwwwW
WW.PPp..PPp..PPp..MMMM.....PPp..PPp..PPp.....WWWW
WW.PPp..PPp..PPp..MmMm.....PPp..PPp..PPp.....WWWW
WW..............................................WW
WWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWW
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDdDDDDDdDDDDDDDDDdDDDDdDDDDDDDDDDdDDDDdDDDDDD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdDDD
DDDDDDdDDDDDDDdDDDDDDDdDDDDdDDDDDDDDDDdDDDDdDDDDDD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdDDDDDDDDDDDDDDDDDDD
DDDDDDdDDDDDdDDDDDDDDDdDDDDdDDDDDDDDDDdDDDDdDDDDDD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DD..........DD..........DD..........DD..........DD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
`, WORKSHOP_PAL);

// Weapon rack (1x3 tiles = 16x48 pixels)
const weaponRack = createSprite(`
..DDDDDDDDDDDD..
..DD.MMMMMM.DD..
..DD.MmMmMm.DD..
..DD.MMMMMM.DD..
..DD........DD..
..DD.SsSsSs.DD..
..DD.SsSsSs.DD..
..DD.SsSsSs.DD..
..DD........DD..
..DD.MMMMMM.DD..
..DD.MmMmMm.DD..
..DD.MMMMMM.DD..
..DD........DD..
..DD.SsSsSs.DD..
..DD.SsSsSs.DD..
..DD.SsSsSs.DD..
..DD........DD..
..DD.MMMMMM.DD..
..DD.MmMmMm.DD..
..DD.MMMMMM.DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DD........DD..
..DDDDDDDDDDDD..
DDDDDDDDDDDDDDDD
`, WORKSHOP_PAL);

// Vial shelf (2x1 tiles = 32x16 pixels)
const vialShelf = createSprite(`
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WW.VV.VV.VV.VV.VV.VV.VV.VV.VVW
WW.Vv.Vv.Vv.Vv.Vv.Vv.Vv.Vv.VW
WW.VV.VV.VV.VV.VV.VV.VV.VV.VVW
WW.VV.VV.VV.VV.VV.VV.VV.VV.VVW
WW.VV.VV.VV.VV.VV.VV.VV.VV.VVW
WW.VV.VV.VV.VV.VV.VV.VV.VV.VVW
WW.VV.VV.VV.VV.VV.VV.VV.VV.VVW
WW.Vv.Vv.Vv.Vv.Vv.Vv.Vv.Vv.VW
WW.rr.rr.rr.rr.rr.rr.rr.rr.rW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WwWwWwWwWwWwWwWwWwWwWwWwWwWwWwWw
WW............................WW
WW............................WW
WW............................WW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
`, WORKSHOP_PAL);

// Lantern (1x2 tiles = 16x32 pixels)
const lantern = createSprite(`
.......CC.......
......CccC......
.....Cc..cC.....
.....C.ll.C.....
.....C.lL.C.....
.....C.Ll.C.....
.....C.lL.C.....
.....C.Ll.C.....
.....Cc..cC.....
......CccC......
.......CC.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......bb.......
.......BB.......
`, WORKSHOP_PAL);

// Tome/book stack (1x1 tile = 16x16 pixels)
const tomeStack = createSprite(`
................
................
................
...PPPPPPPP.....
..PPPPPPPPPp....
..PPppPPppPp....
..PPPPPPPPPP....
..PPPPPPPPPp....
.PPPPPPPPPPPp...
.PPppPPppPPPp...
.PPPPPPPPPPPp...
.PPPPPPPPPPPp...
PPPPPPPPPPPPPp..
PPppPPppPPPPPp..
PPPPPPPPPPPPPPP.
PPPPPPPPPPPPPp..
`, WORKSHOP_PAL);

// Anvil (2x1 tiles = 32x16 pixels)
const anvil = createSprite(`
................MMMMMM..........
...............MmmmmmM..........
..............MmmmmmmmM.........
.............MmmmmmmmmmM........
............MmmmmmmmmmmmM.......
...........MMMMMMMMMMMMMmM......
.............MM.......MmM.......
..............M.......MM........
..............M.......M.........
..............M.......M.........
.............MM.......MM........
............MMM.......MMM.......
...........MMMM.......MMMM.....
..........MMMMM.......MMMMM....
.........MMMMMM.......MMMMM....
........MMMMMMM.......MMMMMM...
`, WORKSHOP_PAL);

export const workshopProps: ScenePropDef[] = [
  { name: 'workbench', sprite: workbench, tileX: 2, tileY: 7, actionState: 'inscribe' },
  { name: 'weapon-rack', sprite: weaponRack, tileX: 21, tileY: 3 },
  { name: 'vial-shelf', sprite: vialShelf, tileX: 12, tileY: 3 },
  { name: 'lantern', sprite: lantern, tileX: 5, tileY: 4, actionState: 'meditate' },
  { name: 'tome-stack', sprite: tomeStack, tileX: 12, tileY: 8, actionState: 'read' },
  { name: 'anvil', sprite: anvil, tileX: 17, tileY: 8, actionState: 'forge' },
];

// ============================================
// Firelink Shrine Props
// ============================================

const FIRELINK_PAL: Record<string, string> = {
  'S': '#555550',  // stone
  's': '#666660',  // stone highlight
  'F': '#ff6600',  // fire
  'f': '#ff8800',  // fire bright
  'O': '#ffaa00',  // fire hottest
  'o': '#ffcc00',  // fire brightest
  'W': '#444440',  // wall dark
  'w': '#555550',  // wall highlight
  'C': '#333330',  // charcoal
  'c': '#444440',  // charcoal highlight
  'M': '#888888',  // metal
  'm': '#aaaaaa',  // metal highlight
  'G': '#aa8800',  // gold
  'g': '#886600',  // gold shadow
  'P': '#553322',  // parchment
  'p': '#664433',  // parchment light
  'B': '#3d2b1f',  // wood
  'b': '#4a3828',  // wood highlight
  'D': '#5a5a50',  // stone dark
  'd': '#6a6a60',  // stone highlight
};

// Bonfire (2x2 tiles = 32x32 pixels)
const bonfire = createSprite(`
................o...............
...............oOo..............
..............oOFOo.............
.............oOFFOo.............
............oOFFFOo.............
...........oOOFFOOo.............
..........ooOFFFOOoo............
.........oOOFFFFOOooo...........
........oOOFFFFFOOoo............
........oOFFFFFFOOo.............
.......oOOFFFFFFOo..............
.......oOFFFFFFFOo..............
.......OFFFFFFFFO...............
......OOFFFFFFFFFo..............
.....oOFFFFFFFFFFo..............
.....OOFFFFFFFFFFOO.............
....oOFFffFFFFFfffOO............
....OOFffffFFfffFFfOo...........
...oOFffffFFFfffffFOo...........
...OOFfffFFFFFffffFOo...........
..oOFFffffFFFffffFFOo...........
..OOFFfffFFFFFfffFFOo...........
.oOFFFfffffFffffFFFOo...........
.OOFFFFFffffffFFFFOOo...........
.oCCSSSSSSSSSSSSSSCCo...........
.CCCSSSSSSSSSSSSSSCCC...........
CCSSSSSSSSSSSSSSSSSCC...........
CCSSSSSSSSSSSSSSSSSSCC..........
SSSSSSSSSSSSSSSSSSSSSS..........
SSSSSSSSSSSSSSSSSSSSSSS.........
SSSSSSSSSSSSSSSSSSSSSSSS........
SSSSSSSSSSSSSSSSSSSSSSSsS.......
`, FIRELINK_PAL);

// Stone throne (2x2 tiles = 32x32 pixels)
const stoneThrone = createSprite(`
.......SSSSSSSSSSSSSSSS.........
......SSSSSSSSSSSSSSSSSs........
.....SSSssSSSSSSSSssSSSs........
....SSSSssSSSSSSSSssSSSSs.......
....SSSSSSSSSSSSSSSSSSSS........
....SSSSSSSSSSSSSSSSSSSs........
....SSSSSSSSSSSSSSSSSSSS........
....SSSSSSSSSGGGSSSSSSSSs.......
....SSSSSSSSgGGgSSSSSSSSs.......
....SSSSSSSSSSSSSSSSSSSSS.......
....SSSSSSSSSSSSSSSSSSSSs.......
....SSSSSSSSSSSSSSSSSSSSS.......
....SSSSSSSSSSSSSSSSSSSSs.......
...SSSSSSSSSSSSSSSSSSSSSSs......
...SSSssSSSSSSSSSSSssSSSs.......
..SSSSSsSSSSSSSSSSSSsSSSs.......
..SSSSSsSSSSSSSSSSSsSSSSSs......
..SSSSSsSSSSSSSSSSSsSSSSs.......
..SSSSSsSSSSSSSSSSSSsSSSs.......
..SSSSSsSSSSSSSSSSSsSSSSs.......
..SSSSSsSSSSSSSSSSSsSSSSs.......
..SSSSSsSSSSSSSSSSSsSSSSSs......
..SSSSSsSSSSSSSSSSSsSSSSSs......
..SSSSSsSSSSSSSSSSSsSSSSSs......
..SSSSSsSSSSSSSSSSSsSSSSSs......
..SSSSSSSSSSSSSSSSSSSSSSS.......
..SSSSSSSSSSSSSSSSSSSSSSSs......
..SSSSSSSSSSSSSSSSSSSSSSSs......
.SSSSSSSSSSSSSSSSSSSSSSSSs......
.SSSSSSSSSSSSSSSSSSSSSSSSSs.....
SSSSSSSSSSSSSSSSSSSSSSSSSSs.....
SSSSSSSSSSSSSSSSSSSSSSSSSSSs....
`, FIRELINK_PAL);

// Sword monument (1x3 tiles = 16x48 pixels)
const swordMonument = createSprite(`
.......mm.......
.......mM.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
......mGMm......
.....mGGGMm.....
......mGMm......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.......mM.......
.......Mm.......
.....mmMMMmm....
....mMMMMMMMm...
...SSSSSSSSSSSs.
..SSSSSSSSSSSSSs
..SSSSSSSSSSSSS.
...SSSSSSSSSSS..
....SSSSSSSSS...
.....SSssSsSS...
......SSSSSS....
.......SSSS.....
........SS......
........SS......
.......SSSS.....
......SSSSSS....
`, FIRELINK_PAL);

// Tome pedestal (1x1 tile = 16x16 pixels)
const tomePedestal = createSprite(`
....PPPPPPPP....
...PPppPPppPP...
...PPPPPPPPPP...
...PPppPPppPP...
...PPPPPPPPPP...
....SSSSSSSS....
.....SSSSSS.....
.....SSSSSS.....
.....SSSSSS.....
.....SSSSSS.....
.....SSSSSS.....
....SSSSSSSS....
...SSSSSSSSSS...
..SSSSSSSSSSSS..
.SSSSSSSSSSSSS..
SSSSSSSSSSSSSSSS
`, FIRELINK_PAL);

// Forge anvil (2x1 tiles = 32x16 pixels)
const firelinkAnvil = createSprite(`
................MMMMMM..........
...............MmmmmmM..........
..............MmmmmmmmM.........
.............MmmmmmmmmmM........
............MmmmmmmmmmmmM.......
...........MMMMMMMMMMMMMmM......
.............MM.......MmM.......
..............M.......MM........
..............M.......M.........
..............M.......M.........
.............MM.......MM........
............MMM.......MMM.......
...........MMMM.......MMMM.....
..........MMMMM.......MMMMM....
.........MMMMMM.......MMMMM....
........MMMMMMM.......MMMMMM...
`, FIRELINK_PAL);

// Stone work table (2x1 tiles = 32x16 pixels)
const stoneTable = createSprite(`
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
SsSsSsSsSsSsSsSsSsSsSsSsSsSsSsSs
SS..............................
SS..............................
SS......PP.PP.......PP.PP.......
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.
.SS..........SS..........SS.....
..SS..........SS..........SS....
..SS..........SS..........SS....
..SS..........SS..........SS....
..SS..........SS..........SS....
..SS..........SS..........SS....
..SS..........SS..........SS....
..SS..........SS..........SS....
..SS..........SS..........SS....
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
`, FIRELINK_PAL);

export const firelinkProps: ScenePropDef[] = [
  { name: 'bonfire', sprite: bonfire, tileX: 11, tileY: 5, actionState: 'meditate' },
  { name: 'stone-throne', sprite: stoneThrone, tileX: 1, tileY: 3 },
  { name: 'sword-monument', sprite: swordMonument, tileX: 22, tileY: 2 },
  { name: 'tome-pedestal', sprite: tomePedestal, tileX: 15, tileY: 8, actionState: 'read' },
  { name: 'forge-anvil', sprite: firelinkAnvil, tileX: 18, tileY: 8, actionState: 'forge' },
  { name: 'stone-table', sprite: stoneTable, tileX: 5, tileY: 8, actionState: 'inscribe' },
];

// ============================================
// Site of Grace Props
// ============================================

const GRACE_PAL: Record<string, string> = {
  'G': '#ffd700',  // gold
  'g': '#ccaa00',  // gold shadow
  'Y': '#ffee55',  // gold bright
  'S': '#6a6a5a',  // stone
  's': '#7a7a6a',  // stone light
  'W': '#555548',  // wall stone
  'w': '#656558',  // wall light
  'D': '#3d2b1f',  // wood
  'd': '#4a3828',  // wood highlight
  'P': '#553322',  // parchment
  'p': '#664433',  // parchment light
  'T': '#5a7a3a',  // tree trunk
  't': '#4a6a2a',  // trunk shadow
  'L': '#6a9a3a',  // leaf
  'l': '#7aaa4a',  // leaf bright
  'E': '#8aaa5a',  // leaf light
  'B': '#4a6030',  // branch
  'M': '#888888',  // metal
  'm': '#aaaaaa',  // metal highlight
  'R': '#4a4030',  // root/dirt
  'C': '#5a5a4a',  // column stone
  'c': '#6a6a5a',  // column highlight
};

// Grace stake (1x2 tiles = 16x32 pixels)
const graceStake = createSprite(`
.......GG.......
......gYYg......
.....gYYYYg.....
......gYYg......
.......GG.......
.......GG.......
......gGGg......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
.......GG.......
......SSSS......
.....SSSSSS.....
....SSSSSSSS....
...SSSSSSSSSS...
`, GRACE_PAL);

// Ruined desk (2x1 tiles = 32x16 pixels)
const ruinedDesk = createSprite(`
DDDDDDddDDDDDDdDDDDDDDddDDDDDDD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDdDDD
DD..PPpp..PPpp..PPpp..PPpp....DD
DD..PPpp..PPpp..PPpp..PPpp....DD
DD............................DD
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
.DD..........DD.........DD......
..DD..........DD.........DD.....
..DD..........DD..........D.....
..DD..........DD................
..DD..........DD................
..DD..........DD................
..DD..........DD................
..DD..........DD................
..DD...........D................
DDDDDDDDDDDDDDDD..............
`, GRACE_PAL);

// Stone tablet (1x1 tile = 16x16 pixels)
const stoneTablet = createSprite(`
...SSSSSSSSSS...
..SSSSSSSSSSSs..
..SSssSSssSSS...
..SSSSSSSSSSs...
..SSssSSssSSs...
..SSSSSSSSSSs...
..SSssSSssSSS...
..SSSSSSSSSSs...
..SSssSSssSSs...
..SSSSSSSSSSs...
..SSssSSssSSS...
..SSSSSSSSSSs...
..SSSSSSSSSSs...
..SSSSSSSSSSS...
.SSSSSSSSSSSSS..
SSSSSSSSSSSSSSS.
`, GRACE_PAL);

// Grace anvil (2x1 tiles = 32x16 pixels)
const graceAnvil = createSprite(`
................MMMMMM..........
...............MmmmmmM..........
..............MmmmmmmmM.........
.............MmmmmmmmmmM........
............MmmmmmmmmmmmM.......
...........MMMMMMMMMMMMMmM......
.............MM.......MmM.......
..............M.......MM........
..............M.......M.........
..............M.......M.........
.............MM.......MM........
............MMM.......MMM.......
...........MMMM.......MMMM.....
..........MMMMM.......MMMMM....
.........MMMMMM.......MMMMM....
........MMMMMMM.......MMMMMM...
`, GRACE_PAL);

// Erdtree sapling (2x3 tiles = 32x48 pixels)
const erdtreeSapling = createSprite(`
..............llll..............
............lLLLLLl.............
...........lLLEELLLl............
..........lLLEEEELLl............
.........lLLEEEEELLl...........
........lLLLEEEEELLLl..........
.......lLLLLEEEELLLLLl.........
......lLLLLLLEELLLLLLLl........
.....lLLELLLLLLLLLLELLLl.......
....lLLEELLLLLLLLLLEELLl.......
...lLLEEELLLLLLLLLLEEELLl......
..lLLEEEELLLEELLLLEEEELLl.....
..lLLEEELLLLEEELLLLEEELLl.....
..lLLEELLLLLEEEELLLLEELLl.....
...lLLLLLLLLEEEELLLLLLLl.......
...lLLLLLLLLEEEELLLLLLLl.......
....lLLLLLLLEEELLLLLLLl........
.....lLLLLLLEELLLLLLLl.........
......lLLLLLLLLLLLLLl..........
.......lLLLLLLLLLLLl...........
........lLLLLLLLLLl............
.........lLLLBLLLl.............
..........llBBBll...............
............BTBB................
............BTBB................
...........BTTBB................
...........BTTBB................
..........BBTTTBB...............
..........BBTTTBB...............
.........BBTTTTBBb..............
.........BBTTTTBBb..............
........BBBTTTTBBBb.............
........BBTTTTTTBBb.............
.......BBBTTTTTTBBBb............
.......BBTTTTTTTBBBB............
......BBBTTTTTTTTBBBb...........
.....RRRRRRTTTTRRRRRRRr........
....RRRRRRRRRRRRRRRRRRRr.......
...RRRRRRRRRRRRRRRRRRRRRr......
..RRRRRRRRRRRRRRRRRRRRRRRr.....
.RRRRRRRRRRRRRRRRRRRRRRRRRr....
RRRRRRRRRRRRRRRRRRRRRRRRRRRRR...
RRRRRRRRRRRRRRRRRRRRRRRRRRRRr..
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRr.
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRr
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSsS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSsS
SSSSSSsSSSSSSSSSSSsSSSSSSSSSsSsS
`, GRACE_PAL);

export const graceProps: ScenePropDef[] = [
  { name: 'grace-stake', sprite: graceStake, tileX: 11, tileY: 5, actionState: 'meditate' },
  { name: 'ruined-desk', sprite: ruinedDesk, tileX: 4, tileY: 8, actionState: 'inscribe' },
  { name: 'stone-tablet', sprite: stoneTablet, tileX: 16, tileY: 8, actionState: 'read' },
  { name: 'grace-anvil', sprite: graceAnvil, tileX: 19, tileY: 8, actionState: 'forge' },
  { name: 'erdtree-sapling', sprite: erdtreeSapling, tileX: 10, tileY: 0 },
];
